### ISSUE TITLE
Support String extension for localization

### ISSUE THREAD

**Issue by amosavian** [kayak/SwiftGenStrings#1]
Hi,

I defined this extension for localizing strings, How can I get `strings` file?

```swift
extension String {
    func localized(_ args: CVarArg..., comment: String = "") -> String {
        if args.isEmpty {
            return NSLocalizedString(self, comment: comment)
        } else {
            let format = NSLocalizedString(self, comment: comment)
            return String(format: format, arguments: args)
        }
    }
}

"Hello world!".localized()
let name = "Amir"
"Hello %@".localized(name, comment: "Say hello")
```

**Comment by juraj-blahunka** [comment]
Hi @amosavian,  both `genstrings` and `SwiftGenStrings` parse m/swift files, but they do not evaluate them. `SwiftGenStrings` can only pick up string literals wrapped with `NSLocalizedString`, it is not possible to supply variables instead of string literals as arguments.

Example of `NSLocalizedString` with string literals as arguments:
```
let string = NSLocalizedString("Hello, world!", comment: "comment")
```

Output:
```
$ SwiftGenStrings hello.swift
/* comment */
"Hello, world!" = "Hello, world!";
```

If I wanted to use variables instead of string literals, the string generation would fail:
```
# hello.swift                                                                                                                                                                                                          
let key = "Hello, world!"
let string = NSLocalizedString(key, comment: "")

$ SwiftGenStrings hello.swift 
hello.swift: Invalid identifier 'key'
```

The same failure happens with Apple's genstrings and Objective-C:
```
# hello.m
NSString *key = @"Hello, world!";
id* string = NSLocalizedString(key, @"");

$ genstrings hello.m
Bad entry in file hello.m (line = 2): Argument is not a literal string.
```

**Comment by Johennes** [comment]
The only customisation we offer here is the `-s` flag that allows you to specify the name of a function with the same signature as `NSLocalizedString`. So if you had

``` swift
func localized(_ key: String, comment: String) -> String {
   ...
}
```

you could run it with `-s localized`, just like standard `genstrings`. Anything that changes the signature is not currently supported though.
